### PR TITLE
Custom html buttons

### PR DESCRIPTION
**Pull request by MohsinQK**
added the possibility to add custom button HTML to match project design.
image

### CODE REVIEW

**Comment by Jako** [comment]
Thanks for helping jq.multiInput better. I would prefer to add the default html button code directly to the defaults array.

**Comment by Jako** [comment]
Thanks! There is just one old i18n entry here: https://github.com/Jako/jq.multiInput/blob/1e87d4842a329cc0b408470bce74423827838335/src/js/jq.multiinput.js#L148

**Comment by MohsinQK** [comment]
> Thanks! There is just one old i18n entry here:
> 
> https://github.com/Jako/jq.multiInput/blob/1e87d4842a329cc0b408470bce74423827838335/src/js/jq.multiinput.js#L148

you mean I will remove it?

**Comment by Jako** [comment]
Sorry, I was wrong. The defaults.i18n still exist. Thanks for the PR.

**Pull request merged**
